/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnggaranRouteImport } from './routes/_authenticated/anggaran'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPenerimaanRouteImport } from './routes/_authenticated/penerimaan'
import { Route as AuthenticatedPengeluaranRouteImport } from './routes/_authenticated/pengeluaran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnggaranRoute = AuthenticatedAnggaranRouteImport.update({
  id: '/anggaran',
  path: '/anggaran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenerimaanRoute = AuthenticatedPenerimaanRouteImport.update({
  id: '/penerimaan',
  path: '/penerimaan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengeluaranRoute =
  AuthenticatedPengeluaranRouteImport.update({
    id: '/pengeluaran',
    path: '/pengeluaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anggaran': typeof AuthenticatedAnggaranRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/penerimaan': typeof AuthenticatedPenerimaanRoute
  '/pengeluaran': typeof AuthenticatedPengeluaranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anggaran': typeof AuthenticatedAnggaranRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/penerimaan': typeof AuthenticatedPenerimaanRoute
  '/pengeluaran': typeof AuthenticatedPengeluaranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anggaran': typeof AuthenticatedAnggaranRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/penerimaan': typeof AuthenticatedPenerimaanRoute
  '/_authenticated/pengeluaran': typeof AuthenticatedPengeluaranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/anggaran' | '/dashboard' | '/penerimaan' | '/pengeluaran'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/anggaran' | '/dashboard' | '/penerimaan' | '/pengeluaran'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anggaran'
    | '/_authenticated/dashboard'
    | '/_authenticated/penerimaan'
    | '/_authenticated/pengeluaran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/anggaran': {
      id: '/_authenticated/anggaran'
      path: '/anggaran'
      fullPath: '/anggaran'
      preLoaderRoute: typeof AuthenticatedAnggaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penerimaan': {
      id: '/_authenticated/penerimaan'
      path: '/penerimaan'
      fullPath: '/penerimaan'
      preLoaderRoute: typeof AuthenticatedPenerimaanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengeluaran': {
      id: '/_authenticated/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof AuthenticatedPengeluaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnggaranRoute: typeof AuthenticatedAnggaranRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPenerimaanRoute: typeof AuthenticatedPenerimaanRoute
  AuthenticatedPengeluaranRoute: typeof AuthenticatedPengeluaranRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnggaranRoute: AuthenticatedAnggaranRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPenerimaanRoute: AuthenticatedPenerimaanRoute,
  AuthenticatedPengeluaranRoute: AuthenticatedPengeluaranRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
