/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnggaranRouteImport } from './routes/_authenticated/anggaran'
import { Route as AuthenticatedBukuPembantuRouteImport } from './routes/_authenticated/buku-pembantu'
import { Route as AuthenticatedDanaDukaRouteImport } from './routes/_authenticated/dana-duka'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKoreksiRouteImport } from './routes/_authenticated/koreksi'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedLaporanBankRouteImport } from './routes/_authenticated/laporan-bank'
import { Route as AuthenticatedLaporanHarianRouteImport } from './routes/_authenticated/laporan-harian'
import { Route as AuthenticatedPenerimaanRouteImport } from './routes/_authenticated/penerimaan'
import { Route as AuthenticatedPengeluaranRouteImport } from './routes/_authenticated/pengeluaran'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedRekapitulasiRouteImport } from './routes/_authenticated/rekapitulasi'
import { Route as AuthenticatedReklasRouteImport } from './routes/_authenticated/reklas'
import { Route as AuthenticatedRincianUangRouteImport } from './routes/_authenticated/rincian-uang'
import { Route as AuthenticatedWartaRouteImport } from './routes/_authenticated/warta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnggaranRoute = AuthenticatedAnggaranRouteImport.update({
  id: '/anggaran',
  path: '/anggaran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBukuPembantuRoute =
  AuthenticatedBukuPembantuRouteImport.update({
    id: '/buku-pembantu',
    path: '/buku-pembantu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDanaDukaRoute = AuthenticatedDanaDukaRouteImport.update({
  id: '/dana-duka',
  path: '/dana-duka',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKoreksiRoute = AuthenticatedKoreksiRouteImport.update({
  id: '/koreksi',
  path: '/koreksi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanBankRoute =
  AuthenticatedLaporanBankRouteImport.update({
    id: '/laporan-bank',
    path: '/laporan-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaporanHarianRoute =
  AuthenticatedLaporanHarianRouteImport.update({
    id: '/laporan-harian',
    path: '/laporan-harian',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenerimaanRoute = AuthenticatedPenerimaanRouteImport.update({
  id: '/penerimaan',
  path: '/penerimaan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengeluaranRoute =
  AuthenticatedPengeluaranRouteImport.update({
    id: '/pengeluaran',
    path: '/pengeluaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRekapitulasiRoute =
  AuthenticatedRekapitulasiRouteImport.update({
    id: '/rekapitulasi',
    path: '/rekapitulasi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReklasRoute = AuthenticatedReklasRouteImport.update({
  id: '/reklas',
  path: '/reklas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRincianUangRoute =
  AuthenticatedRincianUangRouteImport.update({
    id: '/rincian-uang',
    path: '/rincian-uang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWartaRoute = AuthenticatedWartaRouteImport.update({
  id: '/warta',
  path: '/warta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anggaran': typeof AuthenticatedAnggaranRoute
  '/buku-pembantu': typeof AuthenticatedBukuPembantuRoute
  '/dana-duka': typeof AuthenticatedDanaDukaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/koreksi': typeof AuthenticatedKoreksiRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/laporan-bank': typeof AuthenticatedLaporanBankRoute
  '/laporan-harian': typeof AuthenticatedLaporanHarianRoute
  '/penerimaan': typeof AuthenticatedPenerimaanRoute
  '/pengeluaran': typeof AuthenticatedPengeluaranRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/rekapitulasi': typeof AuthenticatedRekapitulasiRoute
  '/reklas': typeof AuthenticatedReklasRoute
  '/rincian-uang': typeof AuthenticatedRincianUangRoute
  '/warta': typeof AuthenticatedWartaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anggaran': typeof AuthenticatedAnggaranRoute
  '/buku-pembantu': typeof AuthenticatedBukuPembantuRoute
  '/dana-duka': typeof AuthenticatedDanaDukaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/koreksi': typeof AuthenticatedKoreksiRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/laporan-bank': typeof AuthenticatedLaporanBankRoute
  '/laporan-harian': typeof AuthenticatedLaporanHarianRoute
  '/penerimaan': typeof AuthenticatedPenerimaanRoute
  '/pengeluaran': typeof AuthenticatedPengeluaranRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/rekapitulasi': typeof AuthenticatedRekapitulasiRoute
  '/reklas': typeof AuthenticatedReklasRoute
  '/rincian-uang': typeof AuthenticatedRincianUangRoute
  '/warta': typeof AuthenticatedWartaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anggaran': typeof AuthenticatedAnggaranRoute
  '/_authenticated/buku-pembantu': typeof AuthenticatedBukuPembantuRoute
  '/_authenticated/dana-duka': typeof AuthenticatedDanaDukaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/koreksi': typeof AuthenticatedKoreksiRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/laporan-bank': typeof AuthenticatedLaporanBankRoute
  '/_authenticated/laporan-harian': typeof AuthenticatedLaporanHarianRoute
  '/_authenticated/penerimaan': typeof AuthenticatedPenerimaanRoute
  '/_authenticated/pengeluaran': typeof AuthenticatedPengeluaranRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/rekapitulasi': typeof AuthenticatedRekapitulasiRoute
  '/_authenticated/reklas': typeof AuthenticatedReklasRoute
  '/_authenticated/rincian-uang': typeof AuthenticatedRincianUangRoute
  '/_authenticated/warta': typeof AuthenticatedWartaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/anggaran'
    | '/buku-pembantu'
    | '/dana-duka'
    | '/dashboard'
    | '/koreksi'
    | '/laporan'
    | '/laporan-bank'
    | '/laporan-harian'
    | '/penerimaan'
    | '/pengeluaran'
    | '/pengguna'
    | '/rekapitulasi'
    | '/reklas'
    | '/rincian-uang'
    | '/warta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/anggaran'
    | '/buku-pembantu'
    | '/dana-duka'
    | '/dashboard'
    | '/koreksi'
    | '/laporan'
    | '/laporan-bank'
    | '/laporan-harian'
    | '/penerimaan'
    | '/pengeluaran'
    | '/pengguna'
    | '/rekapitulasi'
    | '/reklas'
    | '/rincian-uang'
    | '/warta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anggaran'
    | '/_authenticated/buku-pembantu'
    | '/_authenticated/dana-duka'
    | '/_authenticated/dashboard'
    | '/_authenticated/koreksi'
    | '/_authenticated/laporan'
    | '/_authenticated/laporan-bank'
    | '/_authenticated/laporan-harian'
    | '/_authenticated/penerimaan'
    | '/_authenticated/pengeluaran'
    | '/_authenticated/pengguna'
    | '/_authenticated/rekapitulasi'
    | '/_authenticated/reklas'
    | '/_authenticated/rincian-uang'
    | '/_authenticated/warta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/anggaran': {
      id: '/_authenticated/anggaran'
      path: '/anggaran'
      fullPath: '/anggaran'
      preLoaderRoute: typeof AuthenticatedAnggaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buku-pembantu': {
      id: '/_authenticated/buku-pembantu'
      path: '/buku-pembantu'
      fullPath: '/buku-pembantu'
      preLoaderRoute: typeof AuthenticatedBukuPembantuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dana-duka': {
      id: '/_authenticated/dana-duka'
      path: '/dana-duka'
      fullPath: '/dana-duka'
      preLoaderRoute: typeof AuthenticatedDanaDukaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/koreksi': {
      id: '/_authenticated/koreksi'
      path: '/koreksi'
      fullPath: '/koreksi'
      preLoaderRoute: typeof AuthenticatedKoreksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan-bank': {
      id: '/_authenticated/laporan-bank'
      path: '/laporan-bank'
      fullPath: '/laporan-bank'
      preLoaderRoute: typeof AuthenticatedLaporanBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan-harian': {
      id: '/_authenticated/laporan-harian'
      path: '/laporan-harian'
      fullPath: '/laporan-harian'
      preLoaderRoute: typeof AuthenticatedLaporanHarianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penerimaan': {
      id: '/_authenticated/penerimaan'
      path: '/penerimaan'
      fullPath: '/penerimaan'
      preLoaderRoute: typeof AuthenticatedPenerimaanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengeluaran': {
      id: '/_authenticated/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof AuthenticatedPengeluaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekapitulasi': {
      id: '/_authenticated/rekapitulasi'
      path: '/rekapitulasi'
      fullPath: '/rekapitulasi'
      preLoaderRoute: typeof AuthenticatedRekapitulasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reklas': {
      id: '/_authenticated/reklas'
      path: '/reklas'
      fullPath: '/reklas'
      preLoaderRoute: typeof AuthenticatedReklasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rincian-uang': {
      id: '/_authenticated/rincian-uang'
      path: '/rincian-uang'
      fullPath: '/rincian-uang'
      preLoaderRoute: typeof AuthenticatedRincianUangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warta': {
      id: '/_authenticated/warta'
      path: '/warta'
      fullPath: '/warta'
      preLoaderRoute: typeof AuthenticatedWartaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnggaranRoute: typeof AuthenticatedAnggaranRoute
  AuthenticatedBukuPembantuRoute: typeof AuthenticatedBukuPembantuRoute
  AuthenticatedDanaDukaRoute: typeof AuthenticatedDanaDukaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKoreksiRoute: typeof AuthenticatedKoreksiRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedLaporanBankRoute: typeof AuthenticatedLaporanBankRoute
  AuthenticatedLaporanHarianRoute: typeof AuthenticatedLaporanHarianRoute
  AuthenticatedPenerimaanRoute: typeof AuthenticatedPenerimaanRoute
  AuthenticatedPengeluaranRoute: typeof AuthenticatedPengeluaranRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedRekapitulasiRoute: typeof AuthenticatedRekapitulasiRoute
  AuthenticatedReklasRoute: typeof AuthenticatedReklasRoute
  AuthenticatedRincianUangRoute: typeof AuthenticatedRincianUangRoute
  AuthenticatedWartaRoute: typeof AuthenticatedWartaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnggaranRoute: AuthenticatedAnggaranRoute,
  AuthenticatedBukuPembantuRoute: AuthenticatedBukuPembantuRoute,
  AuthenticatedDanaDukaRoute: AuthenticatedDanaDukaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKoreksiRoute: AuthenticatedKoreksiRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedLaporanBankRoute: AuthenticatedLaporanBankRoute,
  AuthenticatedLaporanHarianRoute: AuthenticatedLaporanHarianRoute,
  AuthenticatedPenerimaanRoute: AuthenticatedPenerimaanRoute,
  AuthenticatedPengeluaranRoute: AuthenticatedPengeluaranRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedRekapitulasiRoute: AuthenticatedRekapitulasiRoute,
  AuthenticatedReklasRoute: AuthenticatedReklasRoute,
  AuthenticatedRincianUangRoute: AuthenticatedRincianUangRoute,
  AuthenticatedWartaRoute: AuthenticatedWartaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
